version: '3'
services:
    strapi:
        container_name: strapi
        build:
            context: ./server
            dockerfile: Dockerfile
        image: strapi:latest
        restart: unless-stopped
        env_file: ./server/.env
        volumes:
            - ./server/config:/opt/app/config
            - ./server/src:/opt/app/src
            - ./server/package.json:/opt/package.json
            - ./server/package-lock.json:/opt/package-lock.json # Replace with package-lock.json if using npm
            - ./server/.env:/opt/app/.env
        ports:
            - '1337:1337'
        networks:
            - strapi
        depends_on:
            - strapiDB

    strapiDB:
        container_name: strapiDB
        platform: linux/amd64
        restart: unless-stopped
        env_file: ./db/.env
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: strapi
            MYSQL_ROOT_PASSWORD: strapi
            MYSQL_PASSWORD: strapi
            MYSQL_DATABASE: strapi
        volumes:
            - strapi-data:/var/lib/mysql
        ports:
            - '3306:9999'
        networks:
            - strapi

volumes:
    strapi-data:
        driver: local

networks:
    strapi:
        driver: bridge